I
name: Media Vault

on:
  workflow_dispatch:

jobs:
  run-media-vault:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Media Vault
        run: |
          python3 media_vault.py
