name: Media Vault

on:
  workflow_dispatch:
jobs:
  run-media-vault:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

     
      - name: Run Media Vault
        env:
          TRAKT_CLIENT_ID: ${{ secrets.TRAKT_CLIENT_ID }}
          TRAKT_CLIENT_SECRET: ${{ secrets.TRAKT_CLIENT_SECRET }}
        run: |
          python3 media_vault.py

      
